services:
  app:
    build: .
    container_name: gsi-to-do-list
    ports:
      - "1337:1337"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    environment:
      - VITE_API_URL=https://gsi-interviews.camiapp.net/to-do
